### ISSUE TITLE
Error compiling: declaration within loops

### ISSUE THREAD

**Issue by darknodi** [V3ded/LunarTear#1]
@V3ded name@name:~/Downloads/LunarTear/src$ ls
LunarTear.c
name@name:~/Downloads/LunarTear/src$ sudo gcc LunarTear.c -o LunarTear -pthread -lm
LunarTear.c: In function ‘LunarTear’:
LunarTear.c:562:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(long i = 0; i < finalAmount; i++) {
     ^
LunarTear.c:562:5: note: use option -std=c99 or -std=gnu99 to compile your code
LunarTear.c: In function ‘ThreadInit’:
LunarTear.c:587:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i = 0; i < THREAD_COUNT; i++) {
     ^
LunarTear.c: In function ‘ThreadJoin’:
LunarTear.c:604:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for(int i = 0; i < THREAD_COUNT; i++) {
     ^
name@name:~/Downloads/LunarTear/src$

**Comment by V3ded** [comment]
Which _gcc_ version are you using? This can be simply fixed by either adding a `-std=gnu99` compiler flag or by putting the declarations above loops. See the screenshot here: https://imgur.com/a/bH9uqOR .

**Comment by darknodi** [comment]
@V3ded 

gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 

I have i386 OS cub linux 

intel atom 1.66 1.66 32 bit

**Comment by V3ded** [comment]
Did you try to compile with the flag I provided? Alternatively update your gcc to v7 and try once again.

**Comment by darknodi** [comment]
can I send you compassionatively, 10 $ ( to your id bank tranfser  ) @V3ded

**Comment by V3ded** [comment]
That’s generous of you :). I will pass on the offer though - save up and buy something nice! Can I mark the issue as solved?

**Comment by darknodi** [comment]
the composition ( well-coordinated ) well-speaked ) well-judgeded.
the script of the writing, well-judged. well-pronounced.
Can you add winsock.h module, or any module, that I to, stress, DNS servers of TCP/IP windows, of a

**Comment by darknodi** [comment]
I would want, that, from the script. 

to have two coordination speaking. pronounciation. with c language. 

./LunarTear -h host.com -p 80 -t 100 -p TCP 

./LunarTear -d domain.com --protocol TCP or SYN 

that to sent request, flooding, dns statics from TCP/IP configuration windows, that lan's computers from gaming center, to go timed out. 

i need this for dns-flooding, targeting, the service provider domain. 

finding dns servers.

nslookup .....

1.1.1.1.1 
1.1.1.1.2 
would you want ICMP/SYN flooding..... 
yes. 

sending ICMP/SYN threading...flooding. packet.... numer unlimited 1 /2 /3 /

ctrl c. stopp

**Comment by darknodi** [comment]
@V3ded hermanito ( from Good Lord )

**Comment by darknodi** [comment]
give me one coordination command simple for I have i386 ( 32 bit architecture ) with 2GB ram. 

@V3ded

**Comment by V3ded** [comment]
1) DNS works over UDP, so you can use the UDP portion of the tool for that sort of flooding. 

2) This tool was a single release project. There are no plans to maintain it further (that includes impleneting winsocks as it’s a totally different platform). If you’d like to see another feature implemented within this tool, please create another issue describing your needs. Maybe someone in the opensource community will code them for you.

I will be closing this thread as of now as I can clearly see malicious intent and we have gone off-topic anyways. Please refrain from spamming me further. It takes time to write a response.
